import type {Metadata} from 'next';
import BaseLayout from '@/components/BaseLayout';
import {routing} from '@/config';
import {notFound} from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}
export const dynamicParams = false;

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // (Only necessary when `dynamicParams = false` is commented out)
  if (!routing.locales.includes((await params).locale)) {
    notFound();
  }

  return (
    <BaseLayout>
      <main>{children}</main>
    </BaseLayout>
  );
}
