import type {Metadata} from 'next';
import {getLocale} from '@/utils/getLocale';
import Link from 'next/link.js';
import {routing} from '@/config';
import BaseLayout from '@/components/BaseLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}
export const dynamicParams = false;

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <BaseLayout>
      <div className="flex justify-between">
        <nav className="flex gap-4 py-4">
          <Link href={`/${locale}`}>Home</Link>
          <Link href={`/${locale}/foo`}>Foo</Link>
        </nav>
      </div>
      <main>{children}</main>
      <Link
        className="mt-4 inline-block"
        href={`/${locale === 'en' ? 'de' : 'en'}`}
      >
        Go to /{locale === 'en' ? 'de' : 'en'}
      </Link>
    </BaseLayout>
  );
}
