import type {Metadata} from 'next';
import {getLocale} from '@/utils/getLocale';
import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className="p-4 max-w-lg">
        <div className="flex justify-between">
          <nav className="flex gap-4 py-4 underline">
            <Link href={`/${locale}`}>Home</Link>
            <Link href={`/${locale}/foo`}>Foo</Link>
          </nav>
        </div>
        <main>{children}</main>
        <Link
          className="mt-4 inline-block"
          href={`/${locale === 'en' ? 'de' : 'en'}`}
        >
          Go to /{locale === 'en' ? 'de' : 'en'}
        </Link>
      </body>
    </html>
  );
}
